server:
  address: 127.0.0.1
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: catalog-api
        uri: lb://CATALOG-API
        predicates:
          - Path=/catalogs/**
#        filters:
#        - PrefixPath=/api

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    gateway:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
  client:
    serviceUrl:
      defaultZone: http://192.168.56.1:8761/eureka, http://192.168.119.1:8762/eureka, http://192.168.149.1:8763/eureka

      
---
spring:
  config:
    activate:
      on-profile: standalone

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka    