server:
  address: 127.0.0.1
  port: 8081

spring:
  application:
    name: catalog-api

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
  client:
    serviceUrl:
      defaultZone: http://192.168.56.1:8761/eureka, http://192.168.119.1:8762/eureka, http://192.168.149.1:8763/eureka

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED 
      failureRateThreshold: 50 
      slidingWindowSize: 3
      waitDurationInOpenState: 5000 # OPEN > Half-Open 상태로 변경되기전 기다리는 시간 / 변경전 까지 호출 실패/ 지정된 시간을 넘어서 호출이 있을때 HALF_OPEN으로 변경
      permittedNumberOfCallsInHalfOpenState: 10
      maxWaitDurationInHalfOpenState: 5000
      registerHealthIndicator: true
  instances:
    customerService:
      baseConfig: default

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 3s
      cancelRunningFuture: true
  instances:
    customerService:
      baseConfig: default      
    cbService:
      baseConfig: default
      
resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 5
      maxWaitDuration: 0
  instances:
    cbService:
      baseConfig: default
---
# standalone
spring:
  config:
    activate:
      on-profile: standalone

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka      
---
# catalog-1
server:
  port: 8081

spring:  
  config:
    activate:
      on-profile: catalog-1
---
# catalog-2
server:
  port: 8082

spring:  
  config:
    activate:
      on-profile: catalog-2

  