version: "3"
services:
  mysql:
    container_name: mysql
    user: "${UID}:${GID}"
    image: mariadb:10.4.18
    volumes: 
      - ${DB_CONF_DIR}:/etc/mysql/conf.d
      - ${DB_DATA_DIR}:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pwd1234
