#default
server:
  address: 127.0.0.1
  port: 8085

spring:
  application:
    name: customer-api

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
  client:
    serviceUrl:     
      defaultZone: http://192.168.56.1:8761/eureka, http://192.168.119.1:8762/eureka, http://192.168.149.1:8763/eureka

---
#standalone
spring:  
  config:
    activate:
      on-profile: standalone

eureka:
  client:
    order: 0
    serviceUrl:
      defaultZone: http://192.168.56.1:8761/eureka
      
---
# customer-1
server:
  port: 8085

spring:  
  config:
    activate:
      on-profile: customer-1

eureka:
  client:
    order: 0
---
#customer-2
server:
  port: 8086

spring:  
  config:
    activate:
      on-profile: customer-2

eureka:
  client:
    order: 1      
---
#customer-3
server:
  port: 8087

spring:  
  config:
    activate:
      on-profile: customer-3
      
eureka:
  client:
    order: 2