#default
server:
  address: 127.0.0.1
  port: 8085
  tomcat:
    threads:
      max: 3

spring:
  application:
    name: customer-api

eureka:
  instance:
    appname: customer-api
    prefer-ip-address: true
    ip-address: ${server.address}
    metadata-map:
      isAutoIncludeGateway: 'true'
  client:
    serviceUrl:     
      defaultZone: http://192.168.56.1:8761/eureka, http://172.23.32.1:8762/eureka, http://172.28.96.1:8763/eureka

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
        
---
#standalone
spring:  
  config:
    activate:
      on-profile: standalone

eureka:
  client:
    order: 0
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
      
---
# customer-1
server:
  port: 8085

spring:  
  config:
    activate:
      on-profile: customer-1

eureka:
  client:
    order: 0
---
#customer-2
server:
  port: 8086

spring:  
  config:
    activate:
      on-profile: customer-2

eureka:
  client:
    order: 1      
---
#customer-3
server:
  port: 8087

spring:  
  config:
    activate:
      on-profile: customer-3
      
eureka:
  client:
    order: 2